/**
 * Game8 조건 문자열의 재료·가구 영문명 → 한글 표기 (OP.GG·인게임 용어 참고).
 * 없는 항목은 (any)→(아무거나)만 바꾸고 영문을 유지한다.
 */

function normalizeMaterialKey(name: string): string {
  return name.trim().replace(/\s+/g, " ").toLowerCase();
}

/** 소문자 키 → 한글 (완전 일치) */
const MATERIAL_EN_TO_KO: Record<string, string> = {
  "tall grass": "초록 풀",
  "tall grass (any)": "키 큰 풀 (아무거나)",
  "yellow tall grass": "노란 풀",
  "red tall grass": "빨간 풀",
  "pink tall grass": "분홍 풀",
  "dry tall grass": "메마른 풀숲",
  "smooth tall grass": "보송보송한 풀숲",
  "wildflowers": "들꽃",
  "seashore flowers": "해안의 꽃",
  "mountain flowers": "산지의 꽃",
  "skyland flowers": "부유섬의 꽃",
  "dandy flowers": "댄디 플라워",
  "water": "물",
  "ocean water": "바닷물",
  "muddy water": "진흙탕물",
  "hot-spring water": "온천",
  "waterfall": "폭포",
  "large boulder": "큰 바위",
  "large tree (any)": "큰 나무 (아무거나)",
  "berry tree (any)": "나무열매 나무 (아무거나)",
  "tree stump (any)": "그루터기 (아무거나)",
  "pointy tree": "세모난 나무",
  "large palm tree": "큰 야자나무",
  "hedge (any)": "생울타리 (아무거나)",
  "lighting (any)": "조명 (아무거나)",
  "streetlight (any)": "가로등 (아무거나)",
  "high-up location": "고지대",
  "gravestone": "묘비",
  "campfire": "모닥불",
  "straw stool": "짚 스툴",
  "straw table": "짚 테이블",
  "seat (any)": "의자 (아무거나)",
  "seat (wide)": "넓은 의자",
  "table (any)": "테이블 (아무거나)",
  "table (large)": "큰 테이블",
  "bed (any)": "침대 (아무거나)",
  "closet (any)": "옷장 (아무거나)",
  "dresser (any)": "서랍장 (아무거나)",
  "partition (any)": "칸막이 (아무거나)",
  "sign (any)": "간판 (아무거나)",
  "post (any)": "기둥 (아무거나)",
  "stand (any)": "스탠드 (아무거나)",
  "toy (any)": "장난감 (아무거나)",
  "doll (any)": "인형 (아무거나)",
  "potted plant (any)": "관엽식물 (아무거나)",
  "waste bin (any)": "쓰레기통 (아무거나)",
  "music mat (any)": "음악 매트 (아무거나)",
  "vegetable field (any)": "채소밭 (아무거나)",
  "plated food": "접시 요리",
  "berry basket": "나무열매 바구니",
  "picnic basket": "바구니",
  "first aid kit": "구급상자",
  "punching bag": "펀칭백",
  "punching game": "펀칭 머신",
  "vending machine": "자판기",
  "cardboard boxes": "골판지 상자",
  "wooden crate": "나무 상자",
  "garbage bags": "쓰레기 봉투",
  "garbage bin": "쓰레기통",
  "beach chair": "비치 체어",
  "beach parasol": "파라솔",
  "inflatable boat": "고무보트",
  "cart": "달구지",
  "wooden path": "나무 길",
  "arrow sign": "화살표 간판",
  "wooden birdhouse": "새집",
  "slender candle": "가는 양초",
  "eerie candle": "섬뜩한 양초",
  "mushroom lamp": "버섯 램프",
  "pitcher-plant pot": "통풀 화분",
  "metal drum": "드럼통",
  "control unit": "조작 패널",
  "jumbled cords": "얽힌 전선",
  "castform weather charm": "캐스폼 날씨 부적",
  "(rain) plated food": "(비) 접시 요리",
  "(sun) plated food": "(맑음) 접시 요리",
  "(sun) bonfire": "(맑음) 모닥불",
  "exhibition stand": "전시대",
  "small stage": "작은 무대",
  "spotlight": "스포트라이트",
  "standing mic": "스탠드 마이크",
  "speaker": "스피커",
  "waterwheel kit": "물레방아 키트",
  "furnace kit": "용광로 키트",
  "smooth rock": "매끄러운 바위",
  "molten rock": "용암",
  "lava": "마그마",
  "stalagmites": "종유석",
  "moss": "이끼",
  "mossy boulder": "이끼 낀 바위",
  "duckweed": "개구리밥",
  "water basin": "물받이",
  "shower": "샤워기",
  "hot-spring spout": "온천 급수구",
  "humidifier": "가습기",
  "crossing gate": "건널목 차단기",
  "railway track": "선로",
  "utility pole": "전봇대",
  "traffic cone": "콘",
  "tires": "타이어",
  "tire toy": "타이어 장난감",
  "wheelbarrow": "손수레",
  "sandbags": "모래주머니",
  "treasure": "보물",
  "map and compass": "지도와 나침반",
  "flower backpack": "꽃 무늬 배낭",
  "flower cushion": "꽃 쿠션",
  "flowery table setting": "꽃 테이블 세팅",
  "lunch box": "도시락",
  "hoppip water bottle": "통통코 물병",
  "ribbon cake": "리본 케이크",
  "adventure kit": "모험 키트",
  "professor's treasure trove": "박사의 보물 창고",
  "lost relic (large)": "큰 잡동사니",
  "chansey plant": "럭키 식물",
  "berry bed": "나무열매 침대",
  "berry chair": "나무열매 의자",
  "berry table": "나무열매 테이블",
  "berry table lamp": "나무열매 테이블 램프",
  "log chair": "통나무 의자",
  "log table": "통나무 테이블",
  "log bed": "통나무 침대",
  "garden chair": "가든 체어",
  "garden table": "가든 테이블",
  "garden light": "가든 조명",
  "chic chair": "시크 체어",
  "chic table": "시크 테이블",
  "chic sofa": "시크 소파",
  "cute bed": "큐트 침대",
  "cute table": "큐트 테이블",
  "cute sofa": "큐트 소파",
  "cute dresser": "큐트 서랍장",
  "cute lamp": "큐트 램프",
  "luxury bed": "럭셔리 침대",
  "luxury table": "럭셔리 테이블",
  "luxury sofa": "럭셔리 소파",
  "luxury lamp": "럭셔리 램프",
  "industrial bed": "인더스트리얼 침대",
  "industrial chair": "인더스트리얼 의자",
  "industrial desk": "인더스트리얼 책상",
  "iron bed": "철제 침대",
  "iron chair": "철제 의자",
  "iron table": "철제 테이블",
  "iron pipes": "철 파이프",
  "iron scaffold": "철제 비계",
  "gaming bed": "게이밍 침대",
  "gaming chair": "게이밍 의자",
  "gaming pc": "게이밍 PC",
  "gaming fridge": "게이밍 냉장고",
  "plain bed": "평범한 침대",
  "plain table": "평범한 테이블",
  "plain sofa": "평범한 소파",
  "plain lamp": "평범한 램프",
  "plain chest": "평범한 상자",
  "naptime bed": "낮잠 침대",
  "pop art bed": "팝 아트 침대",
  "pop art sofa": "팝 아트 소파",
  "pop art table": "팝 아트 테이블",
  "poke ball bed": "몬스터볼 침대",
  "poke ball sofa": "몬스터볼 소파",
  "poke ball table": "몬스터볼 테이블",
  "poke ball light": "몬스터볼 조명",
  "antique bed": "앤티크 침대",
  "antique chair": "앤티크 의자",
  "antique closet": "앤티크 옷장",
  "antique dresser": "앤티크 서랍장",
  "resort hammock": "리조트 해먹",
  "resort table": "리조트 테이블",
  "resort sofa": "리조트 소파",
  "resort light": "리조트 조명",
  "kitchen table": "주방 테이블",
  "food counter": "푸드 카운터",
  "counter": "카운터",
  "cooking stove": "가스레인지",
  "microwave oven": "전자레인지",
  "modern sink": "모던 싱크대",
  "sink": "싱크대",
  "frying pan": "프라이팬",
  "cutting board": "도마",
  "bread oven": "빵 오븐",
  "stylish cooking pot": "스타일리시 냄비",
  "cool bass guitar": "쿨 베이스 기타",
  "cool electric guitar": "쿨 일렉 기타",
  "cd player": "CD 플레이어",
  "cd rack": "CD 랙",
  "television": "텔레비전",
  "laptop": "노트북",
  "tablet": "태블릿",
  "arcade machine": "아케이드 기기",
  "computer": "컴퓨터",
  "microscope": "현미경",
  "science experiment": "과학 실험 세트",
  "magazine rack": "잡지꽂이",
  "newspaper": "신문",
  "bookcase": "책장",
  "office chair": "사무용 의자",
  "office desk": "사무용 책상",
  "office locker": "사물함",
  "office shelf": "선반",
  "desk light": "데스크 램프",
  "pencil holder": "연필꽂이",
  "whiteboard": "화이트보드",
  "wall mirror": "벽거울",
  "floor switch": "바닥 스위치",
  "crystal ball": "수정구",
  "torch": "횃불",
  "stone fireplace": "돌 벽난로",
  "firepit": "불 구덩이",
  "cannon": "대포",
  "ship's wheel": "키",
  "canoe": "카누",
  "walkway": "산책로",
  "stepping stones": "디딤돌",
  "perch": "막대 앉은자리",
  "slide": "미끄럼틀",
  "towel rack": "수건 걸이",
  "bathtub": "욕조",
  "big drum": "큰 북",
  "team rocket wall hanging": "로켓단 벽장식",
  "moonlight dance statue kit": "달빛 댄스 동상 키트",
  "photo cutout board": "얼굴 내밀기 보드",
  "menu board": "메뉴판",
  "cash register": "금전등록기",
  "barrel": "나무통",
  "canvas": "캔버스",
  "bike": "자전거",
  "balloons": "풍선",
  "boo-in-the-box": "깜짝 상자",
  "raichu sign": "라이츄 표지판",
  "sign": "표지판",
  "dragonite doll": "망나뇽 인형",
  "eevee doll": "이브이 인형",
  "pikachu doll": "피카츄 인형",
  "pikachu sofa": "피카츄 소파",
  "arcanine doll": "윈디 인형",
  "smelting furnace": "제련로",
  "concrete pipe": "콘크리트 관",
  "iron beam or column": "철제 기둥",
  "sewer-hole cover": "하수구 뚜껑",
  "offering dish": "공물 접시",
  "party platter": "파티 플래터",
  "chocolate cookies": "초콜릿 쿠키",
  "sandwiches": "샌드위치",
  "fried potatoes": "감자튀김",
  "pizza": "피자",
  "soda float": "소다 플로트",
  "shaved ice": "빙수",
  "afternoon tea set": "애프터눈 티 세트",
  "paper party cups": "종이컵",
  "paper": "종이",
  "cleaning supplies": "청소 도구",
  "excavation tools": "발굴 도구",
  "fishing rod": "낚싯대",
  "strength rock": "힘의 바위",
  "stylish hedge": "스타일리시 생울타리",
  "simple cushion": "심플 쿠션",
  "folding chair": "접이식 의자",
  "step stool": "발판",
  "side table": "사이드 테이블",
  "alarm clock": "자명종",
  "small vase": "작은 꽃병",
  "push cart": "밀카트",
  "mug": "머그컵",
};

export function translateMaterialNameEnToKo(name: string): string {
  const key = normalizeMaterialKey(name);
  if (MATERIAL_EN_TO_KO[key]) {
    return MATERIAL_EN_TO_KO[key];
  }
  let s = name.trim();
  s = s.replace(/\(\s*any\s*\)/gi, "(아무거나)");
  s = s.replace(/\(\s*wide\s*\)/gi, "(넓은)");
  s = s.replace(/\(\s*large\s*\)/gi, "(큰)");
  s = s.replace(/\(\s*rain\s*\)/gi, "(비)");
  s = s.replace(/\(\s*sun\s*\)/gi, "(맑음)");
  return s;
}
